name: contact
channels:
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - python=3.12*
  - pip>=25.3
  - django>= 5.2, < 6.0
  - djangorestframework>=3.16.1
  - django-cors-headers==4.9.0
  - gunicorn==23.0.0
